### ISSUE TITLE
Option to hide "Minor - Ignored sniff 'XXX' with message 'XXX' was not matched in report."

### ISSUE THREAD

**Issue by coderpauloo** [forrest79/phpcs-ignores#1]
Hello,

First thanks for your work, incredibly usefull to have a good baseline tool for phpcs.

I was wondering if there would be a possibility to have an option and/or configuration in order to remove the Minor warnings from sniffs in the baseline that are not matched anymore in the report.

The issue is that if for any reason you decide to finally ignore a sniff, or rework a legacy code, you either have to update the baseline, or regenerate it...
Would it be possible to just not report those warnings in order to avoid having tons of Code quality issues in gitlab when you rework code / add a new ignore on a sniff ? 

Also, thinking about it, I wonder if the phpcs would be able to detect errors on the reworked code, if the lines were previously added in the baseline ?

Maybe there is something I'm not understanding, but I am sure your help on this matter will be priceless.

Thanks a lot
Paul

**Comment by forrest79** [comment]
Hi Paul, sorry for the late delay:

about updating baseline) I copied this functionality from PHPStan, where you also must remove ignored messages from your config manually or regenerate the whole baseline. I must admit, that some kind of tool that removes not anymore used ignored sniffs can be handy. But personally, I can live without it and I don't have time to implement it right now.

about reworked code) Maybe I don't fully understand the question. If you change your code and the same error is still there, it's still ignored. Ignoring is based on sniff name, message text and how many times is the same error in a file. If you just reorganize your code, the errors should be still ignored. The one exception is, when in the error message is included for example line number. When you "move" error to the other line, it's not matched anymore, because the error message is different now.

**Comment by coderpauloo** [comment]
Hello

"When you "move" error to the other line, it's not matched anymore, because the error message is different now."

Yes that's the issue we actually have, we have ~500 ignored things but when we move the code of rework it entirely, the errors are not matched in the report anymore. 

Also another case is: if I generate the baseline and the ruleset changes (example deciding to remove a sniff that was in the ruleset before), then I get all the ignored errors from the baseling that are not matched anymore, because the sniff is not longer in the ruleset.

I think it would be nice to have a 3rd bootstrap file just with the option allowing to not put the "was not matched in the report" in the output, I'll check what i can do

Otherwise as you say, best thing is to regen the whole baseline again

**Comment by forrest79** [comment]
Ok, I understand. Most of the sniffs I'm using have no info about a line/column when the error occurs in the message. so I don't have this problem. Preparing some config with ignoring "is no longer matched" should be easy. I will look at it.

**Comment by coderpauloo** [comment]
That would be great ! Thank you a lot 🙏

**Comment by forrest79** [comment]
Hi, it is prepared in the branch `hide-outdated-warnings`, can you test it with your codebase?

**Comment by coderpauloo** [comment]
Hello, will test it this week, thanks a lot !

**Comment by coderpauloo** [comment]
Hello, 

LGTM does the trick, I think you can add it to the list of bootstrappers for the next release 

And again, thanks a lot for this

**Comment by forrest79** [comment]
Thank you for the review, I will prepare the next release.
